[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "renode-run"

rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
# настройка кросскомпиляции программы для архитектуры Cortex-M4
target = "thumbv7em-none-eabihf"